{% set name = "libstempo" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4cd388adba31b86a9279f77116ee618ee77f876016d5a888815930250a101d4d

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.22
    - numpy
    - pip
    - python
    - setuptools
    - tempo2 >=2020.11.1
  run:
    - astropy >=4.1
    - cython >=0.22
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - tempo2 >=2020.11.1

test:
  imports:
    - libstempo

about:
  home: http://vallis.github.io/libstempo/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: libstempo - a Python wrapper for tempo2
  doc_url: http://vallis.github.io/libstempo/
  dev_url: https://github.com/vallis/libstempo
  description: |
    A Python wrapper for tempo2.
extra:
  recipe-maintainers:
    - mattpitkin
    - jellis18
