{% set name = "libstempo" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8fa0329f2797283c7895e7dd0fe424a977f2d255e9c95cc9b20261ecc790810

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - tempo2 >=2020.11.1
  run:
    - astropy-base >=4.1
    - ephem >=3.7.7.1
    - matplotlib-base
    - numpy
    - python
    - pyerfa
    - scipy
    - tempo2 >=2020.11.1

test:
  imports:
    - libstempo
  requires:
    - pytest
  files:
    - test_fakepulsar.py
    - test_imports.py
    - test_pulsar.py
  commands:
    # run units tests
    - python -m pytest test*.py -v -ra

about:
  home: http://vallis.github.io/libstempo/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: libstempo - a Python wrapper for tempo2
  doc_url: http://vallis.github.io/libstempo/
  dev_url: https://github.com/vallis/libstempo
  description: |
    A Python wrapper for tempo2.
extra:
  recipe-maintainers:
    - mattpitkin
    - jellis18
